# Generated by Django 5.2.6 on 2025-12-09 15:49

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('registros_completos', models.BooleanField(default=False, verbose_name='¿Registros completos?')),
                ('observaciones_validacion', models.TextField(blank=True, verbose_name='Obs. Validación')),
                ('alta_clinica_confirmada', models.BooleanField(default=False)),
                ('medico_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_clinica', models.DateTimeField(blank=True, null=True)),
                ('se_entrego_anticonceptivo', models.BooleanField(default=False, verbose_name='¿Se entregó MAC?')),
                ('metodo_anticonceptivo', models.CharField(blank=True, choices=[('ninguno', 'Ninguno / No aplica'), ('diu', 'DIU (Dispositivo Intrauterino)'), ('implante', 'Implante Subdérmico'), ('oral', 'Anticonceptivo Oral (Pastillas)'), ('inyeccion', 'Inyectable'), ('preservativo', 'Preservativos'), ('ligadura', 'Ligadura de Trompas (Esterilización)'), ('otro', 'Otro Método')], default='ninguno', max_length=50, verbose_name='Método entregado')),
                ('alta_administrativa_confirmada', models.BooleanField(default=False)),
                ('administrativo_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_administrativa', models.DateTimeField(blank=True, null=True)),
                ('certificado_generado', models.BooleanField(default=False)),
                ('ruta_certificado', models.CharField(blank=True, max_length=500)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alta',
                'verbose_name_plural': 'Altas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAlta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('registros_completos', models.BooleanField(default=False, verbose_name='¿Registros completos?')),
                ('observaciones_validacion', models.TextField(blank=True, verbose_name='Obs. Validación')),
                ('alta_clinica_confirmada', models.BooleanField(default=False)),
                ('medico_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_clinica', models.DateTimeField(blank=True, null=True)),
                ('se_entrego_anticonceptivo', models.BooleanField(default=False, verbose_name='¿Se entregó MAC?')),
                ('metodo_anticonceptivo', models.CharField(blank=True, choices=[('ninguno', 'Ninguno / No aplica'), ('diu', 'DIU (Dispositivo Intrauterino)'), ('implante', 'Implante Subdérmico'), ('oral', 'Anticonceptivo Oral (Pastillas)'), ('inyeccion', 'Inyectable'), ('preservativo', 'Preservativos'), ('ligadura', 'Ligadura de Trompas (Esterilización)'), ('otro', 'Otro Método')], default='ninguno', max_length=50, verbose_name='Método entregado')),
                ('alta_administrativa_confirmada', models.BooleanField(default=False)),
                ('administrativo_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_administrativa', models.DateTimeField(blank=True, null=True)),
                ('certificado_generado', models.BooleanField(default=False)),
                ('ruta_certificado', models.CharField(blank=True, max_length=500)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Alta',
                'verbose_name_plural': 'historical Altas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
