# Generated by Django 5.2.6 on 2025-10-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('partos', '0001_initial'),
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30, verbose_name='Estado del alta')),
                ('registros_completos', models.BooleanField(default=False, help_text='Validación automática de que madre, parto y RN tienen datos completos', verbose_name='¿Registros completos?')),
                ('observaciones_validacion', models.TextField(blank=True, help_text='Campos faltantes o problemas detectados', verbose_name='Observaciones de validación')),
                ('alta_clinica_confirmada', models.BooleanField(default=False, verbose_name='Alta clínica confirmada')),
                ('medico_confirma', models.CharField(blank=True, max_length=200, verbose_name='Médico que confirma alta clínica')),
                ('fecha_confirmacion_clinica', models.DateTimeField(blank=True, null=True, verbose_name='Fecha confirmación clínica')),
                ('alta_administrativa_confirmada', models.BooleanField(default=False, verbose_name='Alta administrativa confirmada')),
                ('administrativo_confirma', models.CharField(blank=True, max_length=200, verbose_name='Administrativo que confirma alta')),
                ('fecha_confirmacion_administrativa', models.DateTimeField(blank=True, null=True, verbose_name='Fecha confirmación administrativa')),
                ('certificado_generado', models.BooleanField(default=False, verbose_name='¿Certificado PDF generado?')),
                ('ruta_certificado', models.CharField(blank=True, max_length=500, verbose_name='Ruta del certificado PDF')),
                ('fecha_alta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de alta definitiva')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('madre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta', to='pacientes.madre', verbose_name='Madre')),
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta', to='partos.parto', verbose_name='Parto')),
                ('recien_nacido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido')),
            ],
            options={
                'verbose_name': 'Alta',
                'verbose_name_plural': 'Altas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
