# Generated by Django 5.2.6 on 2025-11-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0001_initial'),
        ('pacientes', '0008_madre_estado_salud'),
        ('partos', '0003_parto_acompanante_parto_edad_gestacional_dias_and_more'),
        ('recien_nacidos', '0006_reciennacido_estado_salud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='administrativo_confirma',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alta',
            name='alta_administrativa_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='alta_clinica_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='certificado_generado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha_confirmacion_administrativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha_confirmacion_clinica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='pacientes.madre', verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='medico_confirma',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='alta',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='observaciones_validacion',
            field=models.TextField(blank=True, verbose_name='Obs. Validación'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.parto', verbose_name='Parto'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='recien_nacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='registros_completos',
            field=models.BooleanField(default=False, verbose_name='¿Registros completos?'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='ruta_certificado',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
