# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('altas', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta',
            name='aborto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.aborto', verbose_name='Evento Aborto'),
        ),
        migrations.AddField(
            model_name='alta',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='pacientes.madre', verbose_name='Madre'),
        ),
        migrations.AddField(
            model_name='alta',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.parto', verbose_name='Parto'),
        ),
    ]
