# Generated by Django 5.2.6 on 2025-11-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0002_alter_alta_administrativo_confirma_and_more'),
        ('pacientes', '0008_madre_estado_salud'),
        ('partos', '0003_parto_acompanante_parto_edad_gestacional_dias_and_more'),
        ('recien_nacidos', '0006_reciennacido_estado_salud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='alta',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='pacientes.madre'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='observaciones_validacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.parto'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='recien_nacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='recien_nacidos.reciennacido'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='registros_completos',
            field=models.BooleanField(default=False),
        ),
    ]
