# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('altas', '0002_initial'),
        ('partos', '0001_initial'),
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta',
            name='recien_nacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido'),
        ),
        migrations.AddField(
            model_name='historicalalta',
            name='aborto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.aborto', verbose_name='Evento Aborto'),
        ),
    ]
