# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('altas', '0003_initial'),
        ('pacientes', '0001_initial'),
        ('partos', '0001_initial'),
        ('recien_nacidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalalta',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalalta',
            name='madre',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.madre', verbose_name='Madre'),
        ),
        migrations.AddField(
            model_name='historicalalta',
            name='parto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.parto', verbose_name='Parto'),
        ),
        migrations.AddField(
            model_name='historicalalta',
            name='recien_nacido',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido'),
        ),
    ]
