# Generated by Django 5.2.6 on 2025-12-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0003_alter_alta_estado_alter_alta_madre_and_more'),
        ('pacientes', '0008_madre_estado_salud'),
        ('partos', '0003_parto_acompanante_parto_edad_gestacional_dias_and_more'),
        ('recien_nacidos', '0006_reciennacido_estado_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta',
            name='metodo_anticonceptivo',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno / No aplica'), ('diu', 'DIU (Dispositivo Intrauterino)'), ('implante', 'Implante Subdérmico'), ('oral', 'Anticonceptivo Oral (Pastillas)'), ('inyeccion', 'Inyectable'), ('preservativo', 'Preservativos'), ('ligadura', 'Ligadura de Trompas (Esterilización)'), ('otro', 'Otro Método')], default='ninguno', max_length=50, verbose_name='Método entregado'),
        ),
        migrations.AddField(
            model_name='alta',
            name='se_entrego_anticonceptivo',
            field=models.BooleanField(default=False, verbose_name='¿Se entregó MAC?'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='alta',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='pacientes.madre', verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='observaciones_validacion',
            field=models.TextField(blank=True, verbose_name='Obs. Validación'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='parto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.parto', verbose_name='Parto'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='recien_nacido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido'),
        ),
        migrations.AlterField(
            model_name='alta',
            name='registros_completos',
            field=models.BooleanField(default=False, verbose_name='¿Registros completos?'),
        ),
    ]
