# Generated by Django 5.2.6 on 2025-12-04 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0004_alta_metodo_anticonceptivo_and_more'),
        ('partos', '0004_aborto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta',
            name='aborto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='partos.aborto', verbose_name='Evento Aborto'),
        ),
    ]
