# Generated by Django 5.2.6 on 2025-12-04 16:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altas', '0005_alta_aborto'),
        ('pacientes', '0009_historicalmadre'),
        ('partos', '0006_historicalaborto_historicalparto'),
        ('recien_nacidos', '0008_historicalreciennacido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAlta',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validada', 'Registros Validados'), ('alta_clinica', 'Alta Clínica Confirmada'), ('alta_administrativa', 'Alta Administrativa Confirmada'), ('completada', 'Alta Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('registros_completos', models.BooleanField(default=False, verbose_name='¿Registros completos?')),
                ('observaciones_validacion', models.TextField(blank=True, verbose_name='Obs. Validación')),
                ('alta_clinica_confirmada', models.BooleanField(default=False)),
                ('medico_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_clinica', models.DateTimeField(blank=True, null=True)),
                ('se_entrego_anticonceptivo', models.BooleanField(default=False, verbose_name='¿Se entregó MAC?')),
                ('metodo_anticonceptivo', models.CharField(blank=True, choices=[('ninguno', 'Ninguno / No aplica'), ('diu', 'DIU (Dispositivo Intrauterino)'), ('implante', 'Implante Subdérmico'), ('oral', 'Anticonceptivo Oral (Pastillas)'), ('inyeccion', 'Inyectable'), ('preservativo', 'Preservativos'), ('ligadura', 'Ligadura de Trompas (Esterilización)'), ('otro', 'Otro Método')], default='ninguno', max_length=50, verbose_name='Método entregado')),
                ('alta_administrativa_confirmada', models.BooleanField(default=False)),
                ('administrativo_confirma', models.CharField(blank=True, max_length=200)),
                ('fecha_confirmacion_administrativa', models.DateTimeField(blank=True, null=True)),
                ('certificado_generado', models.BooleanField(default=False)),
                ('ruta_certificado', models.CharField(blank=True, max_length=500)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aborto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.aborto', verbose_name='Evento Aborto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.madre', verbose_name='Madre')),
                ('parto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.parto', verbose_name='Parto')),
                ('recien_nacido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recien_nacidos.reciennacido', verbose_name='Recién Nacido')),
            ],
            options={
                'verbose_name': 'historical Alta',
                'verbose_name_plural': 'historical Altas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
