# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecienNacido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_unico', models.CharField(db_index=True, editable=False, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre RN')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Talla (cm)')),
                ('perimetro_cefalico', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='CC (cm)')),
                ('ap1_latidos', models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="1' Frec. Cardíaca")),
                ('ap1_respiracion', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="1' Respiración")),
                ('ap1_tono', models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="1' Tono Muscular")),
                ('ap1_reflejos', models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="1' Reflejos")),
                ('ap1_color', models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="1' Color")),
                ('ap5_latidos', models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="5' Frec. Cardíaca")),
                ('ap5_respiracion', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="5' Respiración")),
                ('ap5_tono', models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="5' Tono Muscular")),
                ('ap5_reflejos', models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="5' Reflejos")),
                ('ap5_color', models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="5' Color")),
                ('apgar_1_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 1' Total")),
                ('apgar_5_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 5' Total")),
                ('apgar_10_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 10'")),
                ('condicion_nacimiento', models.CharField(choices=[('vivo', 'Vivo'), ('mortinato', 'Mortinato')], default='vivo', max_length=20)),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano'), ('observacion', 'Obs.'), ('critico', 'Crítico')], default='observacion', max_length=20)),
                ('estado_alta', models.CharField(choices=[('hospitalizado', 'Hosp.'), ('en_proceso', 'Alta Proc.'), ('alta_administrativa', 'Egresado')], default='hospitalizado', max_length=20)),
                ('alerta_revisada', models.BooleanField(default=False)),
                ('lactancia_precoz', models.BooleanField(default=False)),
                ('apego_piel_a_piel', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=True)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('responsable_vacuna_vhb', models.CharField(blank=True, max_length=150)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('requiere_derivacion', models.BooleanField(default=False)),
                ('servicio_derivacion', models.CharField(blank=True, max_length=200)),
                ('examenes_realizados', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Recién Nacido',
                'verbose_name_plural': 'historical Recién Nacidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(editable=False, max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre RN')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Talla (cm)')),
                ('perimetro_cefalico', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='CC (cm)')),
                ('ap1_latidos', models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="1' Frec. Cardíaca")),
                ('ap1_respiracion', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="1' Respiración")),
                ('ap1_tono', models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="1' Tono Muscular")),
                ('ap1_reflejos', models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="1' Reflejos")),
                ('ap1_color', models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="1' Color")),
                ('ap5_latidos', models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="5' Frec. Cardíaca")),
                ('ap5_respiracion', models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="5' Respiración")),
                ('ap5_tono', models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="5' Tono Muscular")),
                ('ap5_reflejos', models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="5' Reflejos")),
                ('ap5_color', models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="5' Color")),
                ('apgar_1_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 1' Total")),
                ('apgar_5_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 5' Total")),
                ('apgar_10_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 10'")),
                ('condicion_nacimiento', models.CharField(choices=[('vivo', 'Vivo'), ('mortinato', 'Mortinato')], default='vivo', max_length=20)),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano'), ('observacion', 'Obs.'), ('critico', 'Crítico')], default='observacion', max_length=20)),
                ('estado_alta', models.CharField(choices=[('hospitalizado', 'Hosp.'), ('en_proceso', 'Alta Proc.'), ('alta_administrativa', 'Egresado')], default='hospitalizado', max_length=20)),
                ('alerta_revisada', models.BooleanField(default=False)),
                ('lactancia_precoz', models.BooleanField(default=False)),
                ('apego_piel_a_piel', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=True)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('responsable_vacuna_vhb', models.CharField(blank=True, max_length=150)),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('requiere_derivacion', models.BooleanField(default=False)),
                ('servicio_derivacion', models.CharField(blank=True, max_length=200)),
                ('examenes_realizados', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
