# Generated by Django 5.2.6 on 2025-10-04 01:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(editable=False, help_text='Identificador único del RN', max_length=50, unique=True, verbose_name='Código único')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre (si ya fue asignado)')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1, verbose_name='Sexo')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8.0)], verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(decimal_places=1, help_text='Talla en centímetros', max_digits=4, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(70.0)], verbose_name='Talla (cm)')),
                ('apgar_1_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR al minuto 1')),
                ('apgar_5_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR a los 5 minutos')),
                ('apgar_10_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='APGAR a los 10 minutos')),
                ('condicion_nacimiento', models.CharField(choices=[('vivo', 'Vivo'), ('mortinato', 'Mortinato')], default='vivo', max_length=20, verbose_name='Condición al nacer')),
                ('requiere_derivacion', models.BooleanField(default=False, verbose_name='¿Requiere derivación?')),
                ('servicio_derivacion', models.CharField(blank=True, help_text='Ej: UCI Neonatal, Neonatología', max_length=200, verbose_name='Servicio de derivación')),
                ('vacunas_aplicadas', models.TextField(blank=True, verbose_name='Vacunas aplicadas')),
                ('examenes_realizados', models.TextField(blank=True, verbose_name='Exámenes realizados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones clínicas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partos.parto', verbose_name='Parto')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
