# Generated by Django 5.2.6 on 2025-10-12 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_10_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación de Vitalidad (minuto 10)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_1_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación de Vitalidad (minuto 1)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_5_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntuación de Vitalidad (minuto 5)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=4, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='talla',
            field=models.DecimalField(decimal_places=1, help_text='Talla en centímetros', max_digits=4, verbose_name='Talla (cm)'),
        ),
    ]
