# Generated by Django 5.2.6 on 2025-11-29 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0003_parto_acompanante_parto_edad_gestacional_dias_and_more'),
        ('recien_nacidos', '0003_reciennacido_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciennacido',
            name='vacunas_aplicadas',
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='apego_piel_a_piel',
            field=models.BooleanField(default=False, verbose_name='Apego'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='lactancia_precoz',
            field=models.BooleanField(default=False, verbose_name='Lactancia < 1hr'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='perimetro_cefalico',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='CC (cm)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='profilaxis_ocular',
            field=models.BooleanField(default=True, verbose_name='Profilaxis Ocular'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='responsable_vacuna_vhb',
            field=models.CharField(blank=True, max_length=150, verbose_name='Resp. Vacuna VHB'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vacuna_bcg',
            field=models.BooleanField(default=False, verbose_name='Vacuna BCG'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vacuna_hepatitis_b',
            field=models.BooleanField(default=False, verbose_name='Vacuna Hepatitis B'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_10_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 10'"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_1_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 1'"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_5_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 5'"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='codigo_unico',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='condicion_nacimiento',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('mortinato', 'Mortinato')], default='vivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recien_nacidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='examenes_realizados',
            field=models.TextField(blank=True, verbose_name='Gases/Exámenes'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre RN'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partos.parto'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.DecimalField(decimal_places=3, help_text='Ej: 3.450', max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='requiere_derivacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='servicio_derivacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destino (Ej: UCI, Sala)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='talla',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Talla (cm)'),
        ),
    ]
