# Generated by Django 5.2.6 on 2025-12-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0006_reciennacido_estado_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='alerta_revisada',
            field=models.BooleanField(default=False, verbose_name='Alerta Revisada por Médico'),
        ),
    ]
