# Generated by Django 5.2.6 on 2025-12-04 16:55

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0006_historicalaborto_historicalparto'),
        ('recien_nacidos', '0007_reciennacido_alerta_revisada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecienNacido',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_unico', models.CharField(db_index=True, editable=False, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre RN')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=3, help_text='Ej: 3.450', max_digits=5, verbose_name='Peso (kg)')),
                ('talla', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Talla (cm)')),
                ('perimetro_cefalico', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='CC (cm)')),
                ('apgar_1_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 1'")),
                ('apgar_5_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 5'")),
                ('apgar_10_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 10'")),
                ('condicion_nacimiento', models.CharField(choices=[('vivo', 'Vivo'), ('mortinato', 'Mortinato')], default='vivo', max_length=20)),
                ('lactancia_precoz', models.BooleanField(default=False, verbose_name='Lactancia < 1hr')),
                ('apego_piel_a_piel', models.BooleanField(default=False, verbose_name='Apego')),
                ('profilaxis_ocular', models.BooleanField(default=True, verbose_name='Profilaxis Ocular')),
                ('vacuna_hepatitis_b', models.BooleanField(default=False, verbose_name='Vacuna Hepatitis B')),
                ('responsable_vacuna_vhb', models.CharField(blank=True, max_length=150, verbose_name='Resp. Vacuna VHB')),
                ('vacuna_bcg', models.BooleanField(default=False, verbose_name='Vacuna BCG')),
                ('requiere_derivacion', models.BooleanField(default=False)),
                ('servicio_derivacion', models.CharField(blank=True, max_length=200, verbose_name='Destino (Ej: UCI, Sala)')),
                ('examenes_realizados', models.TextField(blank=True, verbose_name='Gases/Exámenes')),
                ('observaciones', models.TextField(blank=True)),
                ('alerta_revisada', models.BooleanField(default=False, verbose_name='Alerta Revisada por Médico')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('estado_alta', models.CharField(choices=[('hospitalizado', 'Hospitalizado'), ('alta_medica', 'Alta Médica (Esperando Admin)'), ('alta_administrativa', 'Alta Completa (Egresado)')], default='hospitalizado', max_length=20, verbose_name='Estado Alta')),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano / Alta Probable'), ('observacion', 'En Observación'), ('critico', 'Crítico / UCI')], default='observacion', max_length=20, verbose_name='Estado de Salud')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partos.parto')),
            ],
            options={
                'verbose_name': 'historical Recién Nacido',
                'verbose_name_plural': 'historical Recién Nacidos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
