# Generated by Django 5.2.6 on 2025-12-06 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacidos', '0007_reciennacido_alerta_revisada'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='ap1_color',
            field=models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="1' Color"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap1_latidos',
            field=models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="1' Frec. Cardíaca"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap1_reflejos',
            field=models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="1' Reflejos"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap1_respiracion',
            field=models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="1' Respiración"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap1_tono',
            field=models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="1' Tono Muscular"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap5_color',
            field=models.IntegerField(choices=[(0, 'Azul / Pálido'), (1, 'Cuerpo rosado, manos/pies azules'), (2, 'Completamente rosado')], default=0, verbose_name="5' Color"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap5_latidos',
            field=models.IntegerField(choices=[(0, 'Ausente'), (1, '< 100 lpm'), (2, '> 100 lpm')], default=0, verbose_name="5' Frec. Cardíaca"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap5_reflejos',
            field=models.IntegerField(choices=[(0, 'Sin respuesta'), (1, 'Mueca'), (2, 'Tos / Estornudo / Llanto')], default=0, verbose_name="5' Reflejos"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap5_respiracion',
            field=models.IntegerField(choices=[(0, 'Ausente'), (1, 'Lenta / Irregular'), (2, 'Buena / Llanto fuerte')], default=0, verbose_name="5' Respiración"),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='ap5_tono',
            field=models.IntegerField(choices=[(0, 'Flácido'), (1, 'Cierta flexión'), (2, 'Movimiento activo')], default=0, verbose_name="5' Tono Muscular"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='alerta_revisada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apego_piel_a_piel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_1_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 1' Total"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apgar_5_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="APGAR 5' Total"),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='estado_alta',
            field=models.CharField(choices=[('hospitalizado', 'Hosp.'), ('en_proceso', 'Alta Proc.'), ('alta_administrativa', 'Egresado')], default='hospitalizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='estado_salud',
            field=models.CharField(choices=[('sano', 'Sano'), ('observacion', 'Obs.'), ('critico', 'Crítico')], default='observacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='examenes_realizados',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='lactancia_precoz',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='profilaxis_ocular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='responsable_vacuna_vhb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='servicio_derivacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='vacuna_bcg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='vacuna_hepatitis_b',
            field=models.BooleanField(default=False),
        ),
    ]
