# Generated by Django 5.2.6 on 2025-11-30 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_creacion', models.BooleanField(default=True, verbose_name='Registrar creación')),
                ('registrar_actualizacion', models.BooleanField(default=True, verbose_name='Registrar actualización')),
                ('registrar_eliminacion', models.BooleanField(default=True, verbose_name='Registrar eliminación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('modelo_auditado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo a auditar')),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'verbose_name_plural': 'Configuraciones de Auditoría',
                'unique_together': {('modelo_auditado',)},
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('view', 'Ver'), ('login', 'Iniciar sesión'), ('logout', 'Cerrar sesión')], max_length=10, verbose_name='Acción')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores nuevos')),
                ('campos_modificados', models.JSONField(blank=True, null=True, verbose_name='Campos modificados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditoria_r_timesta_ff48d0_idx'), models.Index(fields=['usuario', '-timestamp'], name='auditoria_r_usuario_6f585b_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_r_content_6c2bdc_idx')],
            },
        ),
    ]
