# Generated by Django 5.2.6 on 2025-10-04 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT de la madre (ej: 12345678-9)', max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(60)], verbose_name='Edad')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('controles_prenatales', models.IntegerField(default=0, verbose_name='Número de controles prenatales')),
                ('embarazos_anteriores', models.IntegerField(default=0, verbose_name='Embarazos anteriores')),
                ('patologias', models.TextField(blank=True, help_text='Ej: hipertensión, diabetes gestacional', verbose_name='Patologías')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
