# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMadre',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Edad')),
                ('nacionalidad', models.CharField(default='Chilena', max_length=100, verbose_name='Nacionalidad')),
                ('prevision', models.CharField(choices=[('fonasa_a', 'FONASA A'), ('fonasa_b', 'FONASA B'), ('fonasa_c', 'FONASA C'), ('fonasa_d', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'PARTICULAR'), ('otra', 'OTRA')], default='fonasa_b', max_length=20, verbose_name='Previsión')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('cesfam', models.CharField(blank=True, help_text='Centro de Salud Familiar', max_length=150, verbose_name='CESFAM de Origen')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('alerta_recepcion', models.TextField(blank=True, help_text='Observación crítica al momento de la recepción (Ej: Sangrado, dolor agudo)', verbose_name='Alerta de Ingreso')),
                ('controles_prenatales', models.IntegerField(default=0, verbose_name='N° Controles')),
                ('embarazos_anteriores', models.IntegerField(default=0, verbose_name='Para (Partos previos)')),
                ('patologias', models.TextField(blank=True, help_text='Ej: RNT 38 SEM AEG, HMD', verbose_name='Diagnósticos / Patologías')),
                ('fecha_ingreso', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('estado_alta', models.CharField(choices=[('hospitalizado', 'Hospitalizado'), ('alta_medica', 'Alta Médica (Esperando Admin)'), ('alta_administrativa', 'Alta Completa (Egresado)')], default='hospitalizado', max_length=20, verbose_name='Estado Alta')),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano / Alta Probable'), ('observacion', 'En Observación'), ('critico', 'Crítico / UCI')], default='observacion', max_length=20, verbose_name='Estado de Salud')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Madre',
                'verbose_name_plural': 'historical Madres',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Ej: 12.345.678-9', max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Edad')),
                ('nacionalidad', models.CharField(default='Chilena', max_length=100, verbose_name='Nacionalidad')),
                ('prevision', models.CharField(choices=[('fonasa_a', 'FONASA A'), ('fonasa_b', 'FONASA B'), ('fonasa_c', 'FONASA C'), ('fonasa_d', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'PARTICULAR'), ('otra', 'OTRA')], default='fonasa_b', max_length=20, verbose_name='Previsión')),
                ('direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, verbose_name='Comuna')),
                ('cesfam', models.CharField(blank=True, help_text='Centro de Salud Familiar', max_length=150, verbose_name='CESFAM de Origen')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('alerta_recepcion', models.TextField(blank=True, help_text='Observación crítica al momento de la recepción (Ej: Sangrado, dolor agudo)', verbose_name='Alerta de Ingreso')),
                ('controles_prenatales', models.IntegerField(default=0, verbose_name='N° Controles')),
                ('embarazos_anteriores', models.IntegerField(default=0, verbose_name='Para (Partos previos)')),
                ('patologias', models.TextField(blank=True, help_text='Ej: RNT 38 SEM AEG, HMD', verbose_name='Diagnósticos / Patologías')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_alta', models.CharField(choices=[('hospitalizado', 'Hospitalizado'), ('alta_medica', 'Alta Médica (Esperando Admin)'), ('alta_administrativa', 'Alta Completa (Egresado)')], default='hospitalizado', max_length=20, verbose_name='Estado Alta')),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano / Alta Probable'), ('observacion', 'En Observación'), ('critico', 'Crítico / UCI')], default='observacion', max_length=20, verbose_name='Estado de Salud')),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
