# Generated by Django 5.2.6 on 2025-11-28 01:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_madre_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='madre',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='madre',
            name='nacionalidad',
            field=models.CharField(default='Chilena', max_length=100, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='madre',
            name='prevision',
            field=models.CharField(choices=[('fonasa_a', 'FONASA A'), ('fonasa_b', 'FONASA B'), ('fonasa_c', 'FONASA C'), ('fonasa_d', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'PARTICULAR'), ('otra', 'OTRA')], default='fonasa_b', max_length=20, verbose_name='Previsión'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='controles_prenatales',
            field=models.IntegerField(default=0, verbose_name='N° Controles'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='madres_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(60)], verbose_name='Edad (Calculada)'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='embarazos_anteriores',
            field=models.IntegerField(default=0, verbose_name='Embarazos Previos'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='patologias',
            field=models.TextField(blank=True, help_text='Ej: hipertensión, diabetes', verbose_name='Patologías'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(help_text='Ej: 12345678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
    ]
