# Generated by Django 5.2.6 on 2025-11-29 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_madre_comuna_madre_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='cesfam',
            field=models.CharField(blank=True, help_text='Centro de Salud Familiar', max_length=150, verbose_name='CESFAM de Origen'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='embarazos_anteriores',
            field=models.IntegerField(default=0, verbose_name='Para (Partos previos)'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='patologias',
            field=models.TextField(blank=True, help_text='Ej: RNT 38 SEM AEG, HMD', verbose_name='Diagnósticos / Patologías'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='prevision',
            field=models.CharField(choices=[('fonasa_a', 'FONASA A'), ('fonasa_b', 'FONASA B'), ('fonasa_c', 'FONASA C'), ('fonasa_d', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'PARTICULAR'), ('otra', 'OTRA')], default='fonasa_b', max_length=20),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(help_text='Ej: 12.345.678-9', max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono'),
        ),
    ]
