# Generated by Django 5.2.6 on 2025-11-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_madre_cesfam_alter_madre_direccion_alter_madre_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='prevision',
            field=models.CharField(choices=[('fonasa_a', 'FONASA A'), ('fonasa_b', 'FONASA B'), ('fonasa_c', 'FONASA C'), ('fonasa_d', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'PARTICULAR'), ('otra', 'OTRA')], default='fonasa_b', max_length=20, verbose_name='Previsión'),
        ),
    ]
