# Generated by Django 5.2.6 on 2025-11-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_madre_prevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='alerta_recepcion',
            field=models.TextField(blank=True, help_text='Observación crítica al momento de la recepción (Ej: Sangrado, dolor agudo)', verbose_name='Alerta de Ingreso'),
        ),
    ]
