# Generated by Django 5.2.6 on 2025-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_madre_alerta_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='estado_alta',
            field=models.CharField(choices=[('hospitalizado', 'Hospitalizado'), ('alta_medica', 'Alta Médica (Esperando Admin)'), ('alta_administrativa', 'Alta Completa (Egresado)')], default='hospitalizado', max_length=20, verbose_name='Estado Alta'),
        ),
    ]
