# Generated by Django 5.2.6 on 2025-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_madre_estado_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='estado_salud',
            field=models.CharField(choices=[('sano', 'Sano / Alta Probable'), ('observacion', 'En Observación'), ('critico', 'Crítico / UCI')], default='observacion', max_length=20, verbose_name='Estado de Salud'),
        ),
    ]
