# Generated by Django 5.2.6 on 2025-12-07 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_madre_estado_salud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='responsable_clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_clinicas_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Matrona Responsable'),
        ),
    ]
