# Generated by Django 5.2.6 on 2025-10-04 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('natural', 'Natural'), ('cesarea', 'Cesárea'), ('instrumental', 'Instrumental')], max_length=20, verbose_name='Tipo de parto')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_hora_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de término')),
                ('tuvo_complicaciones', models.BooleanField(default=False, verbose_name='¿Tuvo complicaciones?')),
                ('complicaciones', models.TextField(blank=True, help_text='Ej: hemorragia, sufrimiento fetal', verbose_name='Descripción de complicaciones')),
                ('medico_responsable', models.CharField(max_length=200, verbose_name='Médico responsable')),
                ('matrona_responsable', models.CharField(max_length=200, verbose_name='Matrona responsable')),
                ('personal_apoyo', models.TextField(blank=True, help_text='Enfermeros y otros profesionales', verbose_name='Personal de apoyo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='pacientes.madre', verbose_name='Madre')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
