# Generated by Django 5.2.6 on 2025-11-29 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_madre_cesfam_alter_madre_direccion_alter_madre_edad_and_more'),
        ('partos', '0002_parto_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='acompanante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Acompañante en Pabellón'),
        ),
        migrations.AddField(
            model_name='parto',
            name='edad_gestacional_dias',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='EG (Días)'),
        ),
        migrations.AddField(
            model_name='parto',
            name='edad_gestacional_semanas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='EG (Semanas)'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='complicaciones',
            field=models.TextField(blank=True, verbose_name='Descripción Complicaciones'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_hora_inicio',
            field=models.DateTimeField(verbose_name='Fecha/Hora Inicio'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_hora_termino',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Nacimiento'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='pacientes.madre'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='matrona_responsable',
            field=models.CharField(max_length=200, verbose_name='Matrona'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='medico_responsable',
            field=models.CharField(max_length=200, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='personal_apoyo',
            field=models.TextField(blank=True, verbose_name='Personal de Apoyo'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo',
            field=models.CharField(choices=[('eutocico', 'Parto Eutócico (Normal)'), ('cesarea_electiva', 'Cesárea Electiva'), ('cesarea_urgencia', 'Cesárea Urgencia'), ('forceps', 'Fórceps'), ('vacuum', 'Vacuum'), ('podalica', 'Podálica')], max_length=30, verbose_name='Tipo de parto'),
        ),
        migrations.AlterField(
            model_name='parto',
            name='tuvo_complicaciones',
            field=models.BooleanField(default=False, verbose_name='¿Complicaciones?'),
        ),
    ]
