# Generated by Django 5.2.6 on 2025-12-04 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_madre_estado_salud'),
        ('partos', '0003_parto_acompanante_parto_edad_gestacional_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aborto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('espontaneo', 'Espontáneo / Incompleto'), ('retenido', 'Hueso / Retenido'), ('ive', 'IVE (Ley 21.030)')], default='espontaneo', max_length=20)),
                ('causal', models.CharField(choices=[('na', 'No Aplica (Espontáneo)'), ('causal_1', 'Causal 1: Riesgo vital materno'), ('causal_2', 'Causal 2: Inviabilidad fetal'), ('causal_3', 'Causal 3: Violación')], default='na', max_length=20)),
                ('fecha_derivacion', models.DateTimeField(auto_now_add=True)),
                ('observacion_matrona', models.TextField(verbose_name='Motivo de Derivación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('derivado', 'Derivado por Matrona (Pendiente)'), ('confirmado', 'Procedimiento Realizado'), ('descartado', 'Descartado / Falsa Alarma')], default='derivado', max_length=20)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abortos', to='pacientes.madre')),
                ('matrona_derivadora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abortos_derivados', to=settings.AUTH_USER_MODEL)),
                ('medico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abortos_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caso Aborto/IVE',
                'verbose_name_plural': 'Casos Aborto/IVE',
            },
        ),
    ]
