# Generated by Django 5.2.6 on 2025-12-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0004_aborto'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='alerta_revisada',
            field=models.BooleanField(default=False, verbose_name='Alerta Revisada por Médico'),
        ),
        migrations.AlterField(
            model_name='aborto',
            name='tipo',
            field=models.CharField(choices=[('espontaneo', 'Espontáneo / Incompleto'), ('retenido', 'Huevo / Retenido'), ('ive', 'IVE (Ley 21.030)')], default='espontaneo', max_length=20),
        ),
    ]
