# Generated by Django 5.2.6 on 2025-12-04 16:55

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_historicalmadre'),
        ('partos', '0005_parto_alerta_revisada_alter_aborto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAborto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('espontaneo', 'Espontáneo / Incompleto'), ('retenido', 'Huevo / Retenido'), ('ive', 'IVE (Ley 21.030)')], default='espontaneo', max_length=20)),
                ('causal', models.CharField(choices=[('na', 'No Aplica (Espontáneo)'), ('causal_1', 'Causal 1: Riesgo vital materno'), ('causal_2', 'Causal 2: Inviabilidad fetal'), ('causal_3', 'Causal 3: Violación')], default='na', max_length=20)),
                ('fecha_derivacion', models.DateTimeField(blank=True, editable=False)),
                ('observacion_matrona', models.TextField(verbose_name='Motivo de Derivación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('derivado', 'Derivado por Matrona (Pendiente)'), ('confirmado', 'Procedimiento Realizado'), ('descartado', 'Descartado / Falsa Alarma')], default='derivado', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.madre')),
                ('matrona_derivadora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico_responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Caso Aborto/IVE',
                'verbose_name_plural': 'historical Casos Aborto/IVE',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalParto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('eutocico', 'Parto Eutócico (Normal)'), ('cesarea_electiva', 'Cesárea Electiva'), ('cesarea_urgencia', 'Cesárea Urgencia'), ('forceps', 'Fórceps'), ('vacuum', 'Vacuum'), ('podalica', 'Podálica')], max_length=30, verbose_name='Tipo de parto')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha/Hora Inicio')),
                ('fecha_hora_termino', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Nacimiento')),
                ('edad_gestacional_semanas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)], verbose_name='EG (Semanas)')),
                ('edad_gestacional_dias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='EG (Días)')),
                ('acompanante', models.CharField(blank=True, max_length=200, verbose_name='Acompañante en Pabellón')),
                ('medico_responsable', models.CharField(max_length=200, verbose_name='Médico')),
                ('matrona_responsable', models.CharField(max_length=200, verbose_name='Matrona')),
                ('personal_apoyo', models.TextField(blank=True, verbose_name='Personal de Apoyo')),
                ('tuvo_complicaciones', models.BooleanField(default=False, verbose_name='¿Complicaciones?')),
                ('complicaciones', models.TextField(blank=True, verbose_name='Descripción Complicaciones')),
                ('observaciones', models.TextField(blank=True)),
                ('alerta_revisada', models.BooleanField(default=False, verbose_name='Alerta Revisada por Médico')),
                ('fecha_registro', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pacientes.madre')),
            ],
            options={
                'verbose_name': 'historical Parto',
                'verbose_name_plural': 'historical Partos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
