# Generated by Django 5.2.6 on 2025-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0005_parto_alerta_revisada_alter_aborto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='estado_alta',
            field=models.CharField(choices=[('hospitalizado', 'Activo / En Sala'), ('alta_administrativa', 'Cerrado / Histórico')], default='hospitalizado', max_length=20, verbose_name='Estado del Evento'),
        ),
    ]
