# Generated by Django 5.2.6 on 2025-12-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partos', '0008_parto_estado_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parto',
            name='estado_alta',
        ),
    ]
