# Generated by Django 5.2.6 on 2025-12-09 15:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('matrona', 'Matrona'), ('administrativo', 'Administrativo'), ('supervisor', 'Supervisor'), ('encargado_ti', 'Encargado TI'), ('recepcionista', 'Recepcionista')], default='administrativo', max_length=20, verbose_name='Rol')),
                ('rut', models.CharField(help_text='RUT del usuario (ej: 12345678-9)', max_length=12, unique=True, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_fallido', 'Login Fallido')], max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=150, verbose_name='Nombre Usuario Intentado')),
                ('exitoso', models.BooleanField(default=True)),
                ('razon_fallo', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Login',
                'verbose_name_plural': 'Auditorías Login',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='usuarios_au_fecha_e_ca169a_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='usuarios_au_usuario_59cd51_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación')], max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo Afectado')),
                ('id_objeto', models.IntegerField(verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Cambio')),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_nuevos', models.JSONField(blank=True, default=dict)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Modificación',
                'verbose_name_plural': 'Auditorías Modificación',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='usuarios_au_fecha_e_48b836_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='usuarios_au_usuario_5efda8_idx'), models.Index(fields=['modelo', 'id_objeto'], name='usuarios_au_modelo_41222e_idx')],
            },
        ),
    ]
