# Generated by Django 5.2.6 on 2025-11-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('matrona', 'Matrona'), ('enfermero', 'Enfermero'), ('administrativo', 'Administrativo'), ('jefatura', 'Jefatura'), ('supervisor', 'Supervisor'), ('encargado_ti', 'Encargado TI')], default='administrativo', max_length=20, verbose_name='Rol'),
        ),
    ]
