# Generated by Django 5.2.6 on 2025-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('matrona', 'Matrona'), ('administrativo', 'Administrativo'), ('supervisor', 'Supervisor'), ('encargado_ti', 'Encargado TI'), ('recepcionista', 'Recepcionista')], default='administrativo', max_length=20, verbose_name='Rol'),
        ),
    ]
