# Generated by Django 5.2.6 on 2025-12-04 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_fallido', 'Login Fallido')], max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, verbose_name='Navegador/Dispositivo')),
                ('nombre_usuario', models.CharField(blank=True, max_length=150, verbose_name='Nombre Usuario Intentado')),
                ('exitoso', models.BooleanField(default=True)),
                ('razon_fallo', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Login',
                'verbose_name_plural': 'Auditorías Login',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='usuarios_au_fecha_e_ca169a_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='usuarios_au_usuario_59cd51_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación')], max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo Afectado')),
                ('id_objeto', models.IntegerField(verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Cambio')),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_nuevos', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_modificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Modificación',
                'verbose_name_plural': 'Auditorías Modificación',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='usuarios_au_fecha_e_48b836_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='usuarios_au_usuario_5efda8_idx'), models.Index(fields=['modelo', 'id_objeto'], name='usuarios_au_modelo_41222e_idx')],
            },
        ),
    ]
