# Generated by Django 5.2.6 on 2025-12-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auditorialogin_auditoriamodificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialogin',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='auditoriamodificacion',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
